= Entity-Relationship Diagrams with PlantUML: A Guide
Jassiel Ovando_F. <jassielof@github.com>
:description: This document is a guide to create Entity-Relationship Diagrams with PlantUML.
:source-highlighter: highlight.js
:toc: auto

[abstract]
== Abstract
This guide leverages the syntax conventions from the `ER Assistant v2.10` tool, developed by jukicn@acm.org, to create Entity-Relationship Diagrams (ERDs) using PlantUML. Adopting these conventions, can produce clear and consistent ERD that are easy to understand and maintain. The current guide provides detailed instructions, examples, and best practices for defining entities, relationships, cardinality, and attributes in/for PlantUML.

== Syntax for PlantUML

=== Entities

Supertype and subtype entities::
* If the entity is a supertype it will be denoted with the relationship line thickness of 2.
** It can be a `-->` or a `--|>` depending on the type of supertype.
** The parameter `skinparam groupInheritance 2` can be used to start join from 2 instead of the default.
But once it's joined, the thickness will be ignored.
* Supertype entities will be inside a rectangle indicating the family of for its subtypes (optional).
* If the supertype entity has the property of being 'disjoint' (`D`) or 'complete' (`C`),
it will be marked over the entity name as `DC` for both or just the single character for each (stereotypes).

NOTE: The `skinparam groupInheritance 2` parameter doesn't work with `-->`.
And if the `skinparam groupInheritance 2` parameter is used, the thickness attribute will be ignored.

Weak entities::
If the entity is a weak entity, it will be marked with a `#line.dashed` after the entity name, so it gets a dashed line border.

Regular entities::
If the entity is a regular entity, it won't have any special markings.

Comments::
https://plantuml.com/class-diagram#59c91a18bcc97bb0[Link to class diagram notes], notes will be used as the comments.

.Example of entities
[plantuml]
----
include::./plantuml/entity.pu[]
----


.Code of the entities
[source,plantuml]
----
include::./plantuml/entity.pu[]
----

=== Attributes

Primary key::
The primary key will be separated from the rest.

Allow null::
If the attribute allows null values, it won't have any special markings.
Otherwise it will have an asterisk `*` before the attribute name.

Foreign key::
If the attribute is a foreign key, it will be bolded.

Comments::
https://plantuml.com/class-diagram#c909b0b5f0434a64[Link to class diagram filed notes], these to be for the attributes.

.Example of attributes
[plantuml]
----
include::./plantuml/attribute.pu[]
----

.Code of the attributes
[source,plantuml]
----
include::./plantuml/attribute.pu[]
----

=== Relationships & Cardinality

https://plantuml.com/ie-diagram#a33822c778959028[Link to the extension of class diagrams] in PlantUML for the relationships cardinality.

Regular::
Denoted with dotted lines.

Identifying::
Denoted with regular lines.

Relationship Attributes::
Use an intermediate entity to represent the relationship with attributes.

.Example of relationships cardinality
[plantuml]
----
include::./plantuml/relationship.pu[]
----

.Code of the relationships cardinality
[source,plantuml]
----
include::./plantuml/relationship.pu[]
----

=== Diagram Notes

For diagram notes, simply use floating notes as given https://plantuml.com/class-diagram#59c91a18bcc97bb0[here].

.Example of diagram notes
[plantuml]
----
include::./plantuml/note.pu[]
----

.Code of the diagram notes
[source,plantuml]
----
include::./plantuml/note.pu[]
----

=== Design Justification

For design justifications, I really couldn't find a workaround but just to keep using notes or using adding them directly into the report.

== Example

.Example of an ERD with all the elements
[plantuml]
----
include::./plantuml/example.pu[]
----

.Code of the ERD
[source,plantuml]
----
include::./plantuml/example.pu[]
----